In [6]:
import pandas as pd
import numpy as np

In [28]:
df=pd.read_csv('/content/creditcard.csv')

In [29]:
df.shape

(284807, 31)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35742 entries, 0 to 35741
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    35742 non-null  int64
 1   V1      35742 non-null  float64
 2   V2      35742 non-null  float64
 3   V3      35742 non-null  float64
 4   V4      35742 non-null  float64
 5   V5      35742 non-null  float64
 6   V6      35741 non-null  float64
 7   V7      35741 non-null  float64
 8   V8      35741 non-null  float64
 9   V9      35741 non-null  float64
 10  V10     35741 non-null  float64
 11  V11     35741 non-null  float64
 12  V12     35741 non-null  float64
 13  V13     35741 non-null  float64
 14  V14     35741 non-null  float64
 15  V15     35741 non-null  float64
 16  V16     35741 non-null  float64
 17  V17     35741 non-null  float64
 18  V18     35741 non-null  float64
 19  V19     35741 non-null  float64
 20  V20     35741 non-null  float64
 21  V21     35741 non-null  float64
 22  V22     35741 non-null  float64
 23  V23     35741 non-null  float64
 24  V24     35741 non-null  float64
 25  V25     35741 non-null  float64
 26  V26     35741 non-null  float64
 27  V27     35741 non-null  float64
 28  V28     35741 non-null  float64
 29  Amount  35741 non-null  float64
 30  Class   35741 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 8.5 MB

In [10]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [11]:
df.dropna(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(140)

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [20]:
df['Class'].value_counts()

Class
0.0    35498
1.0      103
Name: count, dtype: int64

In [19]:
df['Class'].value_counts(normalize=True)*100

Class
0.0    99.710682
1.0     0.289318
Name: proportion, dtype: float64

In [16]:
x=df.drop('Class',axis=1)
y=df['Class']

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(28480, 30) (7121, 30)
(28480,) (7121,)

In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train['Amount']=scaler.fit_transform(x_train['Amount'])
x_test['Amount']=scaler.transform(x_test['Amount'])

In [30]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)

In [31]:
from imblearn.over_sampling import SMOTE
smote= SMOTE(random_state=42)
x_train_smote,y_train_smote=smote.fit_resample(x_train,y_train)

(56796, 30) (56796,)
(28480, 30) (28480,)

In [32]:
print(y_train.value_counts())
print(y_train_smote.value_counts())

Class
0.0    28398
1.0       82
Name: count, dtype: int64
Class
0.0    28398
1.0    28398
Name: count, dtype: int64

In [33]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(x_train_smote,y_train_smote)

LogisticRegression()

In [35]:
y_predict=log.predict(x_test)

In [36]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_predict))

0.9809015587698356

In [42]:
y_train_predict=log.predict(x_train_smote)

In [44]:
accuracy_score(y_train_smote,y_train_predict)

0.9774808085076414

In [45]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

         0.0       1.00      0.98      0.99      7100
         1.0       0.13      1.00      0.24        21

    accuracy                           0.98      7121
   macro avg       0.57      0.99      0.61      7121
weighted avg       1.00      0.98      0.99      7121

In [37]:
print(confusion_matrix(y_test,y_predict))

[[6964  136]
 [   0   21]]

In [46]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(x_train_smote,y_train_smote)

RandomForestClassifier(random_state=42)

In [47]:
y_predict=rf.predict(x_test)

In [48]:
accuracy_score(y_test,y_predict)

0.999157421710434

In [49]:
confusion_matrix(y_test,y_predict)

array([[7096,    4],
       [   2,   19]])

In [51]:
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=42)